configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\debug-build.ps1

# package WEb Appli
build: 
  verbosity: minimal
