//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Strava.NET")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyInformationalVersion("0.1")]
[assembly: AssemblyCopyright("Copyright (c) Colin Gourlay and contributors")]
